#Configuración de la aplicacion
server: 
  port: 8091  address: 0.0.0.0

#Para ver la consola de H2 en el browser
#http://localhost:8091/h2-console
#Habilitando consola h2
spring: 
  h2:
    console:
      enabled: true
  # ======================
  # DB
  # ======================
  datasource:
    url: jdbc:h2:mem:clienteDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password: 
    
  # ======================
  # JPA / HIBERNATE    
  # ======================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate: 
        show-sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

  